const wtf = require('wtf_wikipedia')

wtf.fetch('National_Hockey_League', (err, doc) => {
  let table = doc.sections('list of teams').tables(0)
  console.log(table.keyValue().map((o) => o.Team))
})

/*
[ { Division: 'Atlantic',
    Team: 'Boston Bruins',
    City: 'Boston, Massachusetts',
    Arena: 'TD Garden',
    Capacity: '17,565',
    Founded: '1924',
    Joined: '',
    'General manager': 'Don Sweeney',
    'Head coach': 'Bruce Cassidy',
    Captain: 'Zdeno Chara' },
  { Division: 'Atlantic',
    Team: 'Buffalo Sabres',
    City: 'Buffalo, New York',
    Arena: 'KeyBank Center',
    Capacity: '19,070',
    Founded: '1970',
    Joined: '',
    'General manager': 'Jason Botterill',
    'Head coach': 'Phil Housley',
    Captain: 'Jack Eichel' },
  { Division: 'Atlantic',
    Team: 'Detroit Red Wings',
    City: 'Detroit, Michigan',
    Arena: 'Little Caesars Arena',
    Capacity: '19,515',
    Founded: '1926',
    Joined: '',
    'General manager': 'Ken Holland',
    'Head coach': 'Jeff Blashill',
    Captain: 'Vacant' },
  { Division: 'Atlantic',
    Team: 'Florida Panthers',
    City: 'Sunrise, Florida',
    Arena: 'BB&T Center',
    Capacity: '19,250',
    Founded: '1993',
    Joined: '',
    'General manager': 'Dale Tallon',
    'Head coach': 'Bob Boughner',
    Captain: 'Aleksander Barkov' },
  { Division: 'Atlantic',
    Team: 'Montreal Canadiens',
    City: 'Montreal, Quebec',
    Arena: 'Bell Centre',
    Capacity: '21,302',
    Founded: '1909',
    Joined: '1917',
    'General manager': 'Marc Bergevin',
    'Head coach': 'Claude Julien',
    Captain: 'Shea Weber' },
  { Division: 'Atlantic',
    Team: 'Ottawa Senators',
    City: 'Ottawa, Ontario',
    Arena: 'Canadian Tire Centre',
    Capacity: '17,373',
    Founded: '1992',
    Joined: '',
    'General manager': 'Pierre Dorion',
    'Head coach': 'Guy Boucher',
    Captain: 'Vacant' },
  { Division: 'Atlantic',
    Team: 'Tampa Bay Lightning',
    City: 'Tampa, Florida',
    Arena: 'Amalie Arena',
    Capacity: '19,092',
    Founded: '1992',
    Joined: '',
    'General manager': 'Julien BriseBois',
    'Head coach': 'Jon Cooper',
    Captain: 'Steven Stamkos' },
  { Division: 'Atlantic',
    Team: 'Toronto Maple Leafs',
    City: 'Toronto, Ontario',
    Arena: 'Scotiabank Arena',
    Capacity: '18,819',
    Founded: '1917',
    Joined: '',
    'General manager': 'Kyle Dubas',
    'Head coach': 'Mike Babcock',
    Captain: 'Vacant' },
  { Division: 'Metropolitan',
    Team: 'Carolina Hurricanes',
    City: 'Raleigh, North Carolina',
    Arena: 'PNC Arena',
    Capacity: '18,680',
    Founded: '1972',
    Joined: '1979*',
    'General manager': 'Don Waddell',
    'Head coach': 'Rod Brind\'Amour',
    Captain: 'Justin Williams' },
  { Division: 'Metropolitan',
    Team: 'Columbus Blue Jackets',
    City: 'Columbus, Ohio',
    Arena: 'Nationwide Arena',
    Capacity: '18,144',
    Founded: '2000',
    Joined: '',
    'General manager': 'Jarmo Kekalainen',
    'Head coach': 'John Tortorella',
    Captain: 'Nick Foligno' },
  { Division: 'Metropolitan',
    Team: 'New Jersey Devils',
    City: 'Newark, New Jersey',
    Arena: 'Prudential Center',
    Capacity: '16,514',
    Founded: '1974*',
    Joined: '',
    'General manager': 'Ray Shero',
    'Head coach': 'John Hynes',
    Captain: 'Andy Greene' },
  { Division: 'Metropolitan',
    Team: 'New York Islanders',
    City: 'New York City, New York Uniondale, New York',
    Arena: 'Barclays Center Nassau Coliseum',
    Capacity: '15,795 13,900',
    Founded: '1972',
    Joined: '',
    'General manager': 'Lou Lamoriello',
    'Head coach': 'Barry Trotz',
    Captain: 'Anders Lee' },
  { Division: 'Metropolitan',
    Team: 'New York Rangers',
    City: 'New York City, New York',
    Arena: 'Madison Square Garden',
    Capacity: '18,006',
    Founded: '1926',
    Joined: '',
    'General manager': 'Jeff Gorton',
    'Head coach': 'David Quinn',
    Captain: 'Vacant' },
  { Division: 'Metropolitan',
    Team: 'Philadelphia Flyers',
    City: 'Philadelphia, Pennsylvania',
    Arena: 'Wells Fargo Center',
    Capacity: '19,500',
    Founded: '1967',
    Joined: '',
    'General manager': 'Chuck Fletcher',
    'Head coach': 'Scott Gordon',
    Captain: 'Claude Giroux' },
  { Division: 'Metropolitan',
    Team: 'Pittsburgh Penguins',
    City: 'Pittsburgh, Pennsylvania',
    Arena: 'PPG Paints Arena',
    Capacity: '18,387',
    Founded: '1967',
    Joined: '',
    'General manager': 'Jim Rutherford',
    'Head coach': 'Mike Sullivan',
    Captain: 'Sidney Crosby' },
  { Division: 'Metropolitan',
    Team: 'Washington Capitals',
    City: 'Washington, D.C.',
    Arena: 'Capital One Arena',
    Capacity: '18,506',
    Founded: '1974',
    Joined: '',
    'General manager': 'Brian MacLellan',
    'Head coach': 'Todd Reirden',
    Captain: 'Alexander Ovechkin' },
  { Division: 'Central',
    Team: 'Chicago Blackhawks',
    City: 'Chicago, Illinois',
    Arena: 'United Center',
    Capacity: '19,717',
    Founded: '1926',
    Joined: '',
    'General manager': 'Stan Bowman',
    'Head coach': 'Jeremy Colliton',
    Captain: 'Jonathan Toews' },
  { Division: 'Central',
    Team: 'Colorado Avalanche',
    City: 'Denver, Colorado',
    Arena: 'Pepsi Center',
    Capacity: '18,007',
    Founded: '1972',
    Joined: '1979*',
    'General manager': 'Joe Sakic',
    'Head coach': 'Jared Bednar',
    Captain: 'Gabriel Landeskog' },
  { Division: 'Central',
    Team: 'Dallas Stars',
    City: 'Dallas, Texas',
    Arena: 'American Airlines Center',
    Capacity: '18,532',
    Founded: '1967*',
    Joined: '',
    'General manager': 'Jim Nill',
    'Head coach': 'Jim Montgomery',
    Captain: 'Jamie Benn' },
  { Division: 'Central',
    Team: 'Minnesota Wild',
    City: 'Saint Paul, Minnesota',
    Arena: 'Xcel Energy Center',
    Capacity: '17,954',
    Founded: '2000',
    Joined: '',
    'General manager': 'Paul Fenton',
    'Head coach': 'Bruce Boudreau',
    Captain: 'Mikko Koivu' },
  { Division: 'Central',
    Team: 'Nashville Predators',
    City: 'Nashville, Tennessee',
    Arena: 'Bridgestone Arena',
    Capacity: '17,113',
    Founded: '1998',
    Joined: '',
    'General manager': 'David Poile',
    'Head coach': 'Peter Laviolette',
    Captain: 'Roman Josi' },
  { Division: 'Central',
    Team: 'St. Louis Blues',
    City: 'St. Louis, Missouri',
    Arena: 'Enterprise Center',
    Capacity: '18,724',
    Founded: '1967',
    Joined: '',
    'General manager': 'Doug Armstrong',
    'Head coach': 'Craig Berube',
    Captain: 'Alex Pietrangelo' },
  { Division: 'Central',
    Team: 'Winnipeg Jets',
    City: 'Winnipeg, Manitoba',
    Arena: 'Bell MTS Place',
    Capacity: '15,321',
    Founded: '1999*',
    Joined: '',
    'General manager': 'Kevin Cheveldayoff',
    'Head coach': 'Paul Maurice',
    Captain: 'Blake Wheeler' },
  { Division: 'Pacific',
    Team: 'Anaheim Ducks',
    City: 'Anaheim, California',
    Arena: 'Honda Center',
    Capacity: '17,174',
    Founded: '1993',
    Joined: '',
    'General manager': 'Bob Murray',
    'Head coach': 'Randy Carlyle',
    Captain: 'Ryan Getzlaf' },
  { Division: 'Pacific',
    Team: 'Arizona Coyotes',
    City: 'Glendale, Arizona',
    Arena: 'Gila River Arena',
    Capacity: '17,125',
    Founded: '1972',
    Joined: '1979*',
    'General manager': 'John Chayka',
    'Head coach': 'Rick Tocchet',
    Captain: 'Oliver Ekman-Larsson' },
  { Division: 'Pacific',
    Team: 'Calgary Flames',
    City: 'Calgary, Alberta',
    Arena: 'Scotiabank Saddledome',
    Capacity: '19,289',
    Founded: '1972*',
    Joined: '',
    'General manager': 'Brad Treliving',
    'Head coach': 'Bill Peters',
    Captain: 'Mark Giordano' },
  { Division: 'Pacific',
    Team: 'Edmonton Oilers',
    City: 'Edmonton, Alberta',
    Arena: 'Rogers Place',
    Capacity: '18,347',
    Founded: '1972',
    Joined: '1979',
    'General manager': 'Peter Chiarelli',
    'Head coach': 'Ken Hitchcock',
    Captain: 'Connor McDavid' },
  { Division: 'Pacific',
    Team: 'Los Angeles Kings',
    City: 'Los Angeles, California',
    Arena: 'Staples Center',
    Capacity: '18,230',
    Founded: '1967',
    Joined: '',
    'General manager': 'Rob Blake',
    'Head coach': 'Willie Desjardins',
    Captain: 'Anze Kopitar' },
  { Division: 'Pacific',
    Team: 'San Jose Sharks',
    City: 'San Jose, California',
    Arena: 'SAP Center',
    Capacity: '17,562',
    Founded: '1991',
    Joined: '',
    'General manager': 'Doug Wilson',
    'Head coach': 'Peter DeBoer',
    Captain: 'Joe Pavelski' },
  { Division: 'Pacific',
    Team: 'Vancouver Canucks',
    City: 'Vancouver, British Columbia',
    Arena: 'Rogers Arena',
    Capacity: '18,910',
    Founded: '1945',
    Joined: '1970',
    'General manager': 'Jim Benning',
    'Head coach': 'Travis Green',
    Captain: 'Vacant' },
  { Division: 'Pacific',
    Team: 'Vegas Golden Knights',
    City: 'Paradise, Nevada',
    Arena: 'T-Mobile Arena',
    Capacity: '17,356',
    Founded: '2017',
    Joined: '',
    'General manager': 'George McPhee',
    'Head coach': 'Gerard Gallant',
    Captain: 'Vacant' } ]
    */
